version: '3.1'


volumes:
  mongodb: {}
  mongodb_config: {}

services:

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - ./.env
    command: mongod --port 27017
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.env
